### ISSUE TITLE
Ce fonction est-elle utilisée dans le site finalement?

### ISSUE THREAD

**Issue by alexinstynct** [instynct-solutions-web/Dessercom#18]
https://github.com/instynct-solutions-web/Dessercom/blob/fa5a796a4ecd73fa38d03dab9783d1fb222fc3a2/assets/src/js/modules/_canvas.js#L1

**Comment by Jobarbeau** [comment]
si tu parle de eslint, oui mais pas sur ce qui a trait au canvas.
