### ISSUE TITLE
Je ne suis pas trop sur de comprendre pourquoi il y a deux images qui ont cette classe? hero-slider__image--tablet

### ISSUE THREAD

**Issue by alexinstynct** [instynct-solutions-web/Dessercom#5]
https://github.com/instynct-solutions-web/Dessercom/blob/fa5a796a4ecd73fa38d03dab9783d1fb222fc3a2/templates/tp-home.php#L17

**Comment by Jobarbeau** [comment]
En fait les deux images --tablet semble etre desuet, je les deletes
